In [2]:
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array

In [30]:
def normalization(X):
    return (X/127.5) - 1

datagen = ImageDataGenerator(preprocessing_function=normalization)
train_it = datagen.flow_from_directory('dataset/test_set/', class_mode='binary', batch_size=64, target_size=(64,64),shuffle=False)
print(train_it.class_indices)
print(train_it.labels)
print(train_it.next()[0][0])

Found 2000 images belonging to 2 classes.
{'cats': 0, 'dogs': 1}
[0 0 0 ... 1 1 1]
[[[-0.04313725 -0.2235294  -0.14509803]
  [ 0.10588241 -0.15294117 -0.09803921]
  [-0.17647058 -0.1607843  -0.05882353]
  ...
  [-0.1372549  -0.05882353 -0.04313725]
  [-0.19215685 -0.14509803 -0.05098039]
  [-0.32549018 -0.3490196  -0.29411763]]

 [[-0.03529412 -0.19999999 -0.1607843 ]
  [ 0.1686275   0.14509809  0.21568632]
  [-0.23137254  0.4431373   0.6392157 ]
  ...
  [-0.04313725  0.33333337  0.4901961 ]
  [ 0.13725495  0.6313726   0.77254903]
  [-0.5686275  -0.54509807 -0.49019605]]

 [[-0.05098039 -0.20784312 -0.1372549 ]
  [ 0.09803927  0.04313731  0.09803927]
  [-0.12941176  0.45882356  0.62352943]
  ...
  [ 0.32549024  0.6627451   0.8117647 ]
  [ 0.05882359  0.427451    0.5529412 ]
  [-0.5294118  -0.47450978 -0.42745095]]

 ...

 [[-0.06666666 -0.1607843  -0.1607843 ]
  [-0.08235294  0.07450986  0.00392163]
  [-0.03529412  0.02745104 -0.09019607]
  ...
  [ 0.37254906  0.5294118   0.6       ]
 

In [29]:
def load_i():
    img = load_img('dataset/test_set/cats/cat.4001.jpg', target_size=(64,64))
    img = img_to_array(img)
    # print(img)
    img = normalization(img)
    img = img.reshape(1,64,64,3)
    return img

img = load_i()
print(img) 

[[[[-0.04313725 -0.2235294  -0.14509803]
   [ 0.10588241 -0.15294117 -0.09803921]
   [-0.17647058 -0.1607843  -0.05882353]
   ...
   [-0.1372549  -0.05882353 -0.04313725]
   [-0.19215685 -0.14509803 -0.05098039]
   [-0.32549018 -0.3490196  -0.29411763]]

  [[-0.03529412 -0.19999999 -0.1607843 ]
   [ 0.1686275   0.14509809  0.21568632]
   [-0.23137254  0.4431373   0.6392157 ]
   ...
   [-0.04313725  0.33333337  0.4901961 ]
   [ 0.13725495  0.6313726   0.77254903]
   [-0.5686275  -0.54509807 -0.49019605]]

  [[-0.05098039 -0.20784312 -0.1372549 ]
   [ 0.09803927  0.04313731  0.09803927]
   [-0.12941176  0.45882356  0.62352943]
   ...
   [ 0.32549024  0.6627451   0.8117647 ]
   [ 0.05882359  0.427451    0.5529412 ]
   [-0.5294118  -0.47450978 -0.42745095]]

  ...

  [[-0.06666666 -0.1607843  -0.1607843 ]
   [-0.08235294  0.07450986  0.00392163]
   [-0.03529412  0.02745104 -0.09019607]
   ...
   [ 0.37254906  0.5294118   0.6       ]
   [ 0.4901961   0.6784314   0.75686276]
   [-0.5058824  